In [1]:
import pandas as pd

In [2]:
summary_metrics = pd.read_csv('results/summary_metrics.csv')
factor_metrics = pd.read_csv('results/factor_metrics.csv')

In [3]:
summary_metrics

,Sharpe Ratio,Appraisal Ratio,Alpha T-stat,Skewness,factor,model
0,-0.040651,-0.007745,-0.256471,-14.624502,market_return,simple
1,0.152127,0.070744,2.342721,-6.192932,market_return,complex
2,-0.114127,-0.033081,-1.098822,0.274779,HML,simple
3,0.244217,0.045090,1.497698,4.089224,HML,complex
4,0.059444,0.019702,0.573733,-9.998050,accurals,simple
5,0.513919,0.059921,1.744889,0.897760,accurals,complex
6,0.094271,0.067410,2.209709,0.369613,short_term_reversal,simple
7,0.279497,0.011212,0.367525,-3.714586,short_term_reversal,complex
8,0.006718,-0.007818,-0.260253,-4.366936,value,simple
9,0.120718,0.052152,1.736152,-0.065267,value,complex
10,-0.020466,-0.010109,-0.336226,7.807050,size,simple
11,0.223902,0.024851,0.826534,13.225652,size,complex
12,0.020312,-0.029580,-0.981915,-11.303992,seasonality,simple
13,0.042665,0.015205,0.504721,1.479268,seasonality,complex
14,-0.035960,0.050735,1.388141,-9.302452,debt_issuance,simple
15,0.681958,-0.014909,-0.407907,4.057582,debt_issuance,complex
16,-0.090194,-0.037489,-1.247542,-5.325921,profitability,simple
17,0.036358,0.008023,0.266981,-8.677978,profitability,complex
18,0.033432,-0.041260,-1.337811,12.175667,investment,simple
19,0.195967,-0.017336,-0.562112,9.393809,investment,complex
20,0.008771,0.002235,0.074446,9.100862,quality,simple
21,-0.031241,-0.034280,-1.141715,-10.048935,quality,complex
22,-0.004924,0.005572,0.185817,0.169190,low_leverage,simple
23,0.074259,0.014142,0.471645,-0.130630,low_leverage,complex
24,-0.012203,-0.006419,-0.214111,-2.291572,low_risk,simple
25,0.054883,0.015484,0.516516,-0.388417,low_risk,complex
26,-0.093436,-0.033684,-1.120517,-0.344014,momentum,simple
27,0.057311,-0.020682,-0.688001,-6.907308,momentum,complex
28,-0.132972,-0.023618,-0.782658,-5.217712,profit_growth,simple
29,-0.024311,-0.105521,-3.496759,-22.579643,profit_growth,complex

In [4]:
factor_metrics

    factor_sharpe  factor_skew               factor
0        0.433810     0.378340        market_return
1        0.317982     2.191422                  HML
2        0.693153     0.215868             accurals
3        0.643238    -0.524514  short_term_reversal
4        0.225596    -0.896769                value
5        0.266911     5.096381                 size
6        0.355639    -4.930460          seasonality
7        0.974138     0.877658        debt_issuance
8        0.240614     0.082689        profitability
9        0.379805     2.644181           investment
10       0.210769    -6.638989              quality
11       0.084338     1.551567         low_leverage
12       0.059255    -1.000908             low_risk
13       0.276447    -3.623462             momentum
14       0.407189    -5.590225        profit_growth

In [10]:
summary_df = summary_metrics.round(2)
factor_df = factor_metrics.round(2)

# Keep only necessary columns from summary
summary_cols = ['factor', 'model', 'Sharpe Ratio', 'Appraisal Ratio', 'Alpha T-stat', 'Skewness']
summary_df = summary_df[summary_cols]

# Prepare per-factor tables
factors = summary_df['factor'].unique()

for factor in factors:
    model_metrics = summary_df[summary_df['factor'] == factor].set_index('model')
    
    # Create row for the raw factor itself
    factor_row = factor_df[factor_df['factor'] == factor]
    if not factor_row.empty:
        row = {
            'Sharpe Ratio': factor_row['factor_sharpe'].values[0],
            'Appraisal Ratio': '-',
            'Alpha T-stat': '-',
            'Skewness': factor_row['factor_skew'].values[0]
        }
        model_metrics.loc['factor'] = row

    # Drop 'factor' column for display
    model_metrics = model_metrics.drop(columns='factor', errors='ignore')
    
    print(f"\n=== {factor} ===")
    display(model_metrics)

=== market_return ===

         Sharpe Ratio Appraisal Ratio Alpha T-stat  Skewness
model
simple          -0.04           -0.01        -0.26    -14.62
complex          0.15            0.07         2.34     -6.19
factor           0.43               -            -      0.38

=== HML ===

         Sharpe Ratio Appraisal Ratio Alpha T-stat  Skewness
model
simple          -0.11           -0.03         -1.1      0.27
complex          0.24            0.05          1.5      4.09
factor           0.32               -            -      2.19

=== accurals ===

         Sharpe Ratio Appraisal Ratio Alpha T-stat  Skewness
model
simple           0.06            0.02         0.57    -10.00
complex          0.51            0.06         1.74      0.90
factor           0.69               -            -      0.22

=== short_term_reversal ===

         Sharpe Ratio Appraisal Ratio Alpha T-stat  Skewness
model
simple           0.09            0.07         2.21      0.37
complex          0.28            0.01         0.37     -3.71
factor           0.64               -            -     -0.52

=== value ===

         Sharpe Ratio Appraisal Ratio Alpha T-stat  Skewness
model
simple           0.01           -0.01        -0.26     -4.37
complex          0.12            0.05         1.74     -0.07
factor           0.23               -            -     -0.90

=== size ===

         Sharpe Ratio Appraisal Ratio Alpha T-stat  Skewness
model
simple          -0.02           -0.01        -0.34      7.81
complex          0.22            0.02         0.83     13.23
factor           0.27               -            -      5.10

=== seasonality ===

         Sharpe Ratio Appraisal Ratio Alpha T-stat  Skewness
model
simple           0.02           -0.03        -0.98    -11.30
complex          0.04            0.02          0.5      1.48
factor           0.36               -            -     -4.93

=== debt_issuance ===

         Sharpe Ratio Appraisal Ratio Alpha T-stat  Skewness
model
simple          -0.04            0.05         1.39     -9.30
complex          0.68           -0.01        -0.41      4.06
factor           0.97               -            -      0.88

=== profitability ===

         Sharpe Ratio Appraisal Ratio Alpha T-stat  Skewness
model
simple          -0.09           -0.04        -1.25     -5.33
complex          0.04            0.01         0.27     -8.68
factor           0.24               -            -      0.08

=== investment ===

         Sharpe Ratio Appraisal Ratio Alpha T-stat  Skewness
model
simple           0.03           -0.04        -1.34     12.18
complex          0.20           -0.02        -0.56      9.39
factor           0.38               -            -      2.64

=== quality ===

         Sharpe Ratio Appraisal Ratio Alpha T-stat  Skewness
model
simple           0.01             0.0         0.07      9.10
complex         -0.03           -0.03        -1.14    -10.05
factor           0.21               -            -     -6.64

=== low_leverage ===

         Sharpe Ratio Appraisal Ratio Alpha T-stat  Skewness
model
simple          -0.00            0.01         0.19      0.17
complex          0.07            0.01         0.47     -0.13
factor           0.08               -            -      1.55

=== low_risk ===

         Sharpe Ratio Appraisal Ratio Alpha T-stat  Skewness
model
simple          -0.01           -0.01        -0.21     -2.29
complex          0.05            0.02         0.52     -0.39
factor           0.06               -            -     -1.00

=== momentum ===

         Sharpe Ratio Appraisal Ratio Alpha T-stat  Skewness
model
simple          -0.09           -0.03        -1.12     -0.34
complex          0.06           -0.02        -0.69     -6.91
factor           0.28               -            -     -3.62

=== profit_growth ===

         Sharpe Ratio Appraisal Ratio Alpha T-stat  Skewness
model
simple          -0.13           -0.02        -0.78     -5.22
complex         -0.02           -0.11         -3.5    -22.58
factor           0.41               -            -     -5.59